//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaciaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalles_kit
    {
        public int fk_kit { get; set; }
        public int fk_medicamento { get; set; }
        public decimal descuento { get; set; }
        public decimal costo_total { get; set; }
        public int cantidad { get; set; }
    
        public virtual kit kit { get; set; }
        public virtual medicamento medicamento { get; set; }
    }
}
