//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaciaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalles_notificaciones
    {
        public bool estado { get; set; }
        public int fk_registro { get; set; }
        public int fk_notificacion { get; set; }
    
        public virtual registro registro { get; set; }
        public virtual notificaciones notificaciones { get; set; }
    }
}
