//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaciaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public factura()
        {
            this.detalle_factura = new HashSet<detalle_factura>();
        }
    
        public int id_factura { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> costo_envio { get; set; }
        public Nullable<System.DateTime> fecha_venta { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public Nullable<int> fk_tipo_venta { get; set; }
        public Nullable<int> fk_registro { get; set; }
        public int fk_promocion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura> detalle_factura { get; set; }
        public virtual registro registro { get; set; }
        public virtual tipo_venta tipo_venta { get; set; }
        public virtual promocion promocion { get; set; }
    }
}
