//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaciaWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class arqfarmaciaEntities : DbContext
    {
        public arqfarmaciaEntities()
            : base("name=arqfarmaciaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<detalle_factura> detalle_factura { get; set; }
        public virtual DbSet<detalle_pedido> detalle_pedido { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<forma_pago> forma_pago { get; set; }
        public virtual DbSet<inventario> inventario { get; set; }
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<medicamento> medicamento { get; set; }
        public virtual DbSet<nivel_acceso> nivel_acceso { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
        public virtual DbSet<promocion> promocion { get; set; }
        public virtual DbSet<proveedor> proveedor { get; set; }
        public virtual DbSet<registro> registro { get; set; }
        public virtual DbSet<sucursal> sucursal { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipo_medicamento> tipo_medicamento { get; set; }
        public virtual DbSet<tipo_venta> tipo_venta { get; set; }
        public virtual DbSet<vendedor> vendedor { get; set; }
        public virtual DbSet<detalles_notificaciones> detalles_notificaciones { get; set; }
        public virtual DbSet<notificaciones> notificaciones { get; set; }
    }
}
