//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaciaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inventario()
        {
            this.detalle_factura = new HashSet<detalle_factura>();
        }
    
        public int id_inventario { get; set; }
        public Nullable<int> fk_medicamento { get; set; }
        public Nullable<int> fk_sucursal { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio_venta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura> detalle_factura { get; set; }
        public virtual medicamento medicamento { get; set; }
        public virtual sucursal sucursal { get; set; }
    }
}
