//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaciaWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class kit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kit()
        {
            this.detalles_kit = new HashSet<detalles_kit>();
        }
    
        public int id_kit { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe ingresar el nombre del kit")]
        public string nombre { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe ingresar una descripción")]
        public string descripcion { get; set; }
        public decimal costo { get; set; }
        public decimal ahorro { get; set; }
        public int cantidad_med { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalles_kit> detalles_kit { get; set; }
    }
}
