//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaciaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendedor
    {
        public int id_vendedor { get; set; }
        public string carnet { get; set; }
        public Nullable<decimal> salario { get; set; }
        public int fk_registro { get; set; }
        public int fk_sucursal { get; set; }
    
        public virtual registro registro { get; set; }
        public virtual sucursal sucursal { get; set; }
    }
}
